---
layout: post
title: "A tough week"
date: 2019-11-30
---

This past week was one of the hardest in country so far for a couple reasons. First is a topic I have been avoiding talking about because I just don’t know how to portray it in words. That is the topic of corporal punishment. Peace Corps has 3 main goals and they are as follows:
1.	Helping the people of interested countries in meeting their need for trained men and women 
2.	Helping promote a better understanding of Americans on the part of the peoples served 
3.	Helping promote a better understanding of other peoples on the part of Americans 
As part of these goals I am very careful of what I write in my blogs about Tanzania and my experiences here. So with that being said I will do my best to share about my understanding and experiences of corporal punishment in Tanzanian school systems but if anyone has further questions or clarification please reach out to me. 

In Tanzanian school systems corporal punishment is legal under the National Corporal Punishment Regulations of 1979 following the National Education Act of 1978. These regulations are updated and authorized by the Minister of Education. The rules provide guidance on when corporal punishment should be issued and to what extent. Various parts of the law state that:
-	corporal punishment should be administered in the event of serious misconduct or serious offense committed in or outside of the school which will result in disrespect to the school
-	corporal punishment should be imposed taking into account the age, gender, and health of the student and should not exceed 4 strokes in any event
-	the law requires the headmaster of the school concerned to administer corporal punishment or to suspend his authority with great care to any teacher to administer it
-	every corporal punishment when given should have a record of the punishment included in a book stating the name of the student, the offense committed, the number of strokes and the name of the teacher who administered the punishment. The record must then be signed by the head of school

I don’t have the exact rules or wording on hand at the moment but there are also rules regarding the length, diameter and rigidity of the sticks used in corporal punishment, the location on the body where corporal punishment is to be carried out (on the palm of the hand for girls and on either the butt or palm of the hand for boys), and who is to carry out the punishment (female students are only supposed to receive corporal punishment from female teachers). I hope that gives a little more information in regards to the laws and regulations surrounding corporal punishment in the Tanzanian school system.

I wanted to take time to address this topic in detail because for most of you reading this back home if I were simply to say there was a lot of chapa today (chapa is the word used for “to hit with a stick”) you would automatically think that it is horrible and there should not be corporal punishment in schools. However, I think it is important to understand it in more detail. No, I am not saying I agree with teachers hitting students, but I do understand it in a sense. I understand that most people in Tanzania, and the teachers themselves, grew up with chapa. This has been the primary form of discipline for decades and it is all they know. If you were raised with corporal punishment you would believe that it is okay and that it is how you are supposed to carry out discipline. It is instilled in the culture here. Another thing to keep in mind is that many people in Tanzania, both teachers and parents, honestly believe that they are helping children and students by hitting them. They believe that by feeling pain they will learn from their mistakes. This idea is ingrained in the culture and minds of many people in Tanzania and that is not something that will change overnight. 

That being said, although there are rules and regulations in place they are not always followed. For example, I have seen almost all teachers (not the head master) at both my current school and my internship school administer corporal punishment. I have never once seen a book where the administration of corporal punishment was recorded. Corporal punishment has been administered for a large variety of reasons, many of which I personally would not qualify as “an event of serious misconduct or serious offense”. Some examples of reasons students have received corporal punishment are: not wearing the proper school uniform, failing to bring firewood when they were assigned to do so, not having their hair cut to an acceptable length, receiving a bad grade on an exam, failing to return a textbook at the end of the year, failing to pay their school fees on time, I could go on and on but I’m sure you get the picture. I shared in a previous post about the long list of responsibilities students have in schools and failing to carry out any one of those can result in corporal punishment. Now, I know the “offenses” I just listed seem crazy to many of you reading this. You are probably be thinking, “students get hit for having their hair too long?!” and you are valid in thinking that. I think that too all the time. However it is extremely important to remember what I mentioned before, that this is part of the culture in Tanzania. It is not just one person making these rules or one person carrying out these punishments. This is something that is occurring throughout all of Tanzania and has for decades. 

Yes, I have seen it. Yes, I have seen it beyond what is legally allowed by law. Yes, it is hard to see and yes, sometimes I need to just leave school, go home and cry a little bit. This was a topic discussed multiple times throughout training and it one of the biggest challenges Peace Corps Volunteers in Tanzania have. Because it is legal in Tanzania, we don’t have to like it but we cannot change it. We can have conversations with teachers about our views and share other discipline strategies in hopes that change will come with time but we cannot change it on our own. Because of that, it is important to not focus on the challenges, but to focus on the good things that I've seen and experienced and the good conversations I've had. 

So, after a long week at site I had a few highlights over the weekend. Saturday I went into Lushoto town and went to Lawns hotel to use their Wi-Fi to get some work done. As I was sitting there I was informed that Alikiba was there. Alikiba is a famous bongo flava artist in Tanzania and he was there shooting a music video. 

"Bongo flava is a nickname for Tanzanian hip hop music. The genre, which is based out of the city of Dar es Salaam, takes its name from the Swahili word 'ubongo,' meaning “brains”. Bongo Flava incorporates Afrobeat and arabesque melodies, dancehall and hip hop beats, Swahili lyrics and English phrases, combining aspects of the global hip hop scene with an East African flavor to form a unique style of music." https://www.last.fm/tag/bongo+flava/wiki

I and a couple other volunteers got join Alikiba as he had breakfast to talk with him and then got to meet his entire crew. We got to watch as they filmed for his new music video. It was super cool meeting him and watching them shoot his video. That evening a couple other volunteers and I treated ourselves to a nice dinner and then shared a room in town. It was a nice relaxing girls night hanging out with them.

Another moment that was bittersweet occurred because of deer season opening weekend. Now those of you who know me well know that I am from a huge hunting family and opening weekend of deer season is the one time of year that everyone is together. My cousin Kim was great and put together a little flat Stanley of me and went around taking pictures of me with family and friends. She also called me and the phone was passed around and I was able to talk with everyone. It was sad to miss the big family tradition this year but it was special to be able to be a part of it even from afar. 

Now, as I am finally getting around to finishing this blog post, after a crazy week of grading exams and filling out students' final end of the year grade reports I would like to share about my Thanksgiving. Thanksgiving day I traveled from my site to my friend Abby's site in a village near Same (what normally would take 6-7 hours took me 12, but I made it!). There, I spent the evening with Abby and Jess who are volunteers that came to Tanzania with me as well as Abby's brother and two other girls who were all visiting Abby having just completed a 4 month study abroad program in Tanzania, Kenya and Rwanda. The six of us hung out, made dinner and watched the new Lion King. Friday we went back into Same town where we met up with other volunteers from my cohort, the Education 2018 cohort and the Health/Ag cohort that arrived in February. We all hung out Friday evening and then Saturday celebrated Friendsgiving. We rented out a guesti (similar to a motel) and were able to use their kitchen to prepare our feast. It was nice being able to spend the holidays together. 

So, it the true spirit of Thanksgiving, I want to conclude this post by saying that although there are hard days when I see a lot of chapa or am missing family traditions back home, I am thankful for having friends and family at home that are supporting me in this journey and making sure I know that I am loved and missed when I cannot be there. I am thankful for the friends I have made here who support me and are there for me when I need a break after a long week or who I can spend the holidays with when I cannot be home with family. And I am thankful for all of the good times, conversations and experiences I have had throughout this journey here in Tanzania.


{% for image in site.static_files %}
    {% if image.path contains 'img/a_tough_week' %}
<figure>
<img src="{{ site.baseurl }}{{ image.path }}" style="width:60%" alt="image"/>
</figure>
    {% endif %}
{% endfor %}
