---
layout: post
title: "Holiday Adventures Part 1"
date: 2020-01-11
---

Sorry to keep everyone waiting, I know many of you are curious to hear about and see pictures of my adventures the past few weeks but it takes a very long time to upload pictures on Tanzanian internet, even when I do go to town to get Wi-Fi. Anyway, as I mentioned in my last post I went to Baku and Dubai over the holidays. I think it will be easiest to just give a timeline and then add to each day with more information as I see fit. 

December 17, 2019
Left my site to go to Arusha (city closer to the airport). Devon also met me in Arusha being we had the same flight out. We stayed the night at Roberts, another volunteer from our cohort who is living in a village just outside of Arusha.

December 18, 2019
Explored Arusha with Devon and Robert. We went pile shopping. Pile shopping is exactly how it sounds. Vendors set up like a big market with piles and piles of clothes, shoes, coats, backpacks, blankets, anything you could think of really. It is like a Goodwill on steroids. You can just walk through isles upon isles of things looking through and bargaining for what you want. After spending the day in Arusha we went back to Roberts to gather our things before heading to the airport for a 10:45pm flight. The flight was delayed about an hour and then we flew overnight into Dubai, had a 4 hour layover and then flew to Azerbaijan. 

December 19, 2019
The morning was all flights and a layover in Dubai. We met up with Steve who flew out of Zanzibar originally but also had a layover in Dubai. When we finally got to Azerbaijan we got a taxi to the hotel. The hotel we stayed in was very fancy! Steve’s friend, the groom of the wedding we attended, reserved the hotel for us and got us a huge discount! After freshening up in the hotel and getting settled we went out to dinner with the bride and groom as well as a large group of their friends. Steve went to high school with the groom in Brussels, then they happened to go to the same college in Iowa, ended up working for the same company and also were roommates for 5 years. Needless to say they are very good friends, which is why Steve (along with Devon and I) flew to Azerbaijan for his wedding. So at dinner there were friends from high school, college and past coworkers all present. Being there were people from different stages of their life, Steve and the groom, Tahir, were the only two who knew everyone, the rest of us had a lot of introductions and trying to remember names. Devon and I had it the hardest because we didn’t know anyone other than Steve, but we made it work. Everyone was super friendly and welcoming. Two of the high school friends, Nigar and Kamilla, invited Devon and I to go shopping with them the next day to get a few things for the wedding. We eagerly took them up on the offer being we needed many things (who packs for a fancy wedding when moving to Tanzania for two years?!). 

December 20, 2019
In the morning we walked down to a dress rental store that the bride had told us about because Devon needed a dress for the wedding. I actually had my dress made by a tailor here in Lushoto who does an amazing job. All I had to do was show her a picture, give her the fabric (that I also bought in Lushoto) and let her take my measurements. When I came back to pick it up it fit perfectly, didn’t even need alterations! The dress rental place was an adventure. The lady working did not speak English and we do not speak Azerbaijani or Russian. We ended up calling the groom so that he could translate that we wanted to rent a dress for a wedding (as if the groom didn’t have enough to worry about…oops). But, in the end it worked out and Devon was able to get a dress. In the afternoon we met up with Kamilla and Nigar at the mall and thank goodness we did! They were able to help us translate because most people we interacted with did not speak English. After an entire day of shopping we went back to the hotel to rest before meeting Steve and his friend Bailey for an authentic Azerbaijani dinner. It was amazing. We had a dumpling soup to start and then a mix of other dishes that we all shared so we could try everything. But the most exciting was the kebab tower. It was giant swords of different types of meats. Each sword had either a different type of meat or it was prepared a different way or was seasoned differently. We also had dumplings and an eggplant wrapped dish. There wasn’t one thing I ate that wasn’t amazing. We all left the restaurant stuffed. 

December 21, 2019
Wedding day! In the morning we got up, had breakfast at the hotel and then Devon and I walked down the street to a salon to get our hair done. That was an interesting experience because no one there spoke English and again we didn’t speak their language. We used google translate to say, “we would like to get our hair done for a wedding, do you have time?” and then “how much does it cost?” and then we showed them pictures of what we wanted and sat down. They gave us an option of tea or coffee while we got our hair done. It worked out perfect, and it was cheaper than going out and buying a curling iron and hairspray. After getting our hair done we went back to the hotel and finished getting ready. Once we were all ready we took an uber to the grooms parents’ house where we hung out and had ores devours. Eventually we all headed for the brides parents’ house to pick up the bride. They had a fancy car for the groom and bride and they had rented a big van for all of the friends. At the brides house there was a small ceremony when the groom entered and saw the bride for the first time. There were gifts given by members of the family and some dancing. After that the bride, groom and all of us went to the Four Seasons hotel for pictures. 
Once all the pictures were taken we headed to the reception. It was BEAUTIFUL. I have never been to a wedding this elaborate and fancy. We were escorted to our table which was covered in so many different ores devours and fancy dishes. Each place setting had three plates, three wine glasses, and an abundance of silverware. And the food was just for appetizers. Each table had its own wait staff who served us and cleared our plates. Every time our plate was empty there was more food placed in front of us. If our plate was dirty he would take it away and replace it with a clean one. Eventually after making our way through some of the appetizers they started bringing out main courses. There was a bacon wrapped lamb chop, a rice dish, ice cream and cake. There honestly could have been more that I’m just not remembering because before even starting the main courses I was already full from the ores devours that were on the table. Halfway through the evening I felt so full that I was worried the zipper on my dress would pop. But I pushed forward. You can’t attend a fancy wedding with amazing food and not try things right?? Aside from the food they also kept our glasses full. Water, red wine, white wine or fancy vodka were the main choices. In Azerbaijan it is not common practice to have mixed drinks, they normally drink liquor straight so it took a little convincing and a few failed attempts to explain to the wait staff that we wanted a mixed drink. Eventually, the waiter from the table next to us brought Devon a cocktail. Not sure exactly what it was but it was similar to a mojito. When I requested one also he was hooked. From that point on for the rest of the evening whenever one of us finished a drink he had another one in front of us, and it was always something different and fancy. He also brought a bowl of fresh fruit specially for the two of us, a martini glass filled with pomegranate seeds (the national fruit of Azerbaijan), and when he brought out the ice cream, Devon’s and mine were the only two that had toppings. The two of us had made a friend and were treated to anything we wanted the rest of the evening (as long as we could explain it in a way that he could understand with is very limited English). 
Aside from all the food and drinks there was also dancing. There were two traditional Azerbaijani dances, once when the bride and groom entered and once in the middle of the evening. When everyone was on the dance floor family and friends of the bride and groom taught us Azerbaijani dances. There was also some American music too! The wedding was not only fancy it was also well documented. There were many cameramen around taking pictures and videos. You could have pictures taken and then buy the prints the same night. There was a drone flying around taking video, there was a crane-like thing in the corner that had a video camera on it, everywhere you looked there was a camera. And not only were there cameras everywhere, there were six different screens in the reception hall that you could look up at and see the dance floor. Half way through the evening a video played. Most people thought it would be a how they met or their story type video. No, it was a video from that day, pictures and video clips from the bride and groom getting ready, their first look, and various other parts of the evening. It was beautiful and amazing that they had finished it so quickly. 
After the reception ended (at midnight) instead of going back to hotel to go to sleep like most people would. We all went back to change before going out to the club with the bride and groom. The whole friend group and bride and groom all went to the club for a few hours to hang out and dance more. We finally made it home around 4:30 in the morning.

December 22, 2019
	We got to sleep in a little bit in the morning and then got up to join that same group and the bride and groom back at the Four Seasons for brunch at noon. This was a 5 star brunch. It was a buffet with so much food again there were like 8 different buffet counters. One for donuts and deserts, one for chicken, beef, potatoes and carrots, one for pasta, one for all kinds of salads, an area smoked fish and cheeses, a coffee bar, and I’m pretty sure I saw a sushi bar. It was nuts. If I wasn’t still full from the night before I probably would have enjoyed it more. After brunch we headed out to do the touristy things in Baku before our flight the next morning. We went to the carpet museum, walked the steps up to the flame towers, went to the eternal flame memorial, had dinner in the Old City, wandered around, and went to see Maiden Tower. We were exhausted from the start but we knew we couldn’t go to Azerbaijan only for the wedding and not explore the city so we pushed through and saw as much as we could in our last day.

 



{% for image in site.static_files %}
    {% if image.path contains 'img/Azerbaijan' %}
<figure>
<img src="{{ site.baseurl }}{{ image.path }}" style="width:60%" alt="image"/>
</figure>
    {% endif %}
{% endfor %}
